export const ERROR_STATUS_MAP: Record<string, number> = {
  FIRST_NAME_TOO_LONG: 400,
  FIRST_NAME_TOO_SHORT: 400,
  INVALID_TELEGRAM_ID: 400,
  USER_ALREADY_EXISTS: 409,
  USER_PERSISTENCE_FAILED: 500,
  VALIDATION_ERROR: 400,
  NESTJS_ERROR: 500,
};
