export const ERROR_STATUS_MAP: Record<string, number> = {
  FIRST_NAME_TOO_LONG: 400,
  FIRST_NAME_TOO_SHORT: 400,
  INVALID_TELEGRAM_ID: 400,
  USER_ALREADY_EXISTS: 409,
  USER_PERSISTENCE_FAILED: 500,

  DUPLICATE_URL: 400,
  FAILED_TO_SAVE: 500,
  HANDLE_TO_LONG: 400,
  HANDLE_TO_SHORT: 400,
  INVALID_HANDLE: 400,
  INVALID_PLATFORM: 400,
  NOT_SUPPORTED_PLATFORM: 400,

  VALIDATION_ERROR: 400,
  NESTJS_ERROR: 500,
};
